linux-credentials/libwebauthn

.github/workflows/rust.yml, libwebauthn/src/lib.rs
This crate compiles fine with the latest Rust stable (1.69) if you remove `#![feature(option_get_or_insert_default)]` from `libwebauthn/src/lib.rs`. That feature is not used anywhere here and can be removed.
=> CI: Use Rust stable

libwebauthn/examples/change_pin_hid.rs, libwebauthn/src/pin.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/protocol.rs, libwebauthn/src/transport/error.rs, libwebauthn/src/webauthn.rs
To get a feel for the project, I figured, implementing something smaller might be a good start.
I have 3 TODOs in there: 2 are related to PinTooShort/PinTooLong errors. The platform "should" display this to the user. I currently only return a PinPolicyViolation in both cases, as otherwise I'd need to have platform-specific error-codes that are not specified in the spec. Should be simple enough, if you want me to do it. Otherwise we ignore the "should" and only tell the user something is wrong with the PIN-length.
The third TODO is what to do if the device doesn't even support Pins. Maybe I have overlooked it, but the spec doesn't seem to mention what exact error should be returned in that case. We can abort early, as I'm doing right now, or simply forward a SetPIN-request to the device at …
=> Fix #15: Add SetPIN and ChangePIN

libwebauthn/examples/authenticator_config_hid.rs, libwebauthn/src/lib.rs, libwebauthn/src/management.rs, libwebauthn/src/proto/ctap2/cbor/request.rs, libwebauthn/src/proto/ctap2/mod.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/protocol.rs, libwebauthn/src/webauthn.rs
Refactored `user_verification()` to split out the calculation of `uv_auth_param` so that other commands can implement their own algorithms for it in `calculate_and_set_uv_auth()`.
Needs probably a rebase, once (if) #48 gets merged.
=> Implement AuthenticatorConfig

libwebauthn/src/management.rs, libwebauthn/src/proto/ctap2/mod.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/protocol.rs, libwebauthn/src/transport/ble/channel.rs, libwebauthn/src/transport/cable/channel.rs, libwebauthn/src/transport/channel.rs, libwebauthn/src/transport/hid/channel.rs, libwebauthn/src/transport/mod.rs, libwebauthn/src/webauthn.rs
This is mostly prep-work for upcoming features like BioEnrollments, where we would want to avoid having to enter the PIN for each fingerprint-sample, when enrolling a new fingerprint. Although the `webauthn_hid`-example can already skip one PIN-entry now, too.
I'm aware that `PinProvider` might not be the greatest name now for this trait, but I think it's the right place to add the caching, since it is very related to PINs.
Note: Needs rebase, once #56 lands.
=> Add possibility to cache pinUvAuthToken in PinProvider

libwebauthn/src/pin.rs
The CTAP specification calls out the `alg` value of the PIN protocol's public key must be set to `-25`. From [6.5.6. PIN/UV Auth Protocol One](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#pinProto1):
> getPublicKey()
>    Return a COSE_Key with the following header parameters:
>    * 1 (kty) = 2 (EC2)
>    * 3 (alg) = **-25 (although this is not the algorithm actually used)**
>    * -1 (crv) = 1 (P-256)
>    * -2 (x) = 32-byte, big-endian encoding of the x-coordinate of xB (the [key agreement key](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#puap1keyagmnt-key-agreement-key)'s [public point](https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-t …
=> Fix #59: PIN UV Auth Protocol One: Override pubkey alg to -25 

libwebauthn/src/pin.rs, libwebauthn/src/proto/ctap2/model/client_pin.rs, libwebauthn/src/proto/ctap2/model/get_info.rs, libwebauthn/src/webauthn.rs
For some reason I have not tried my Nitrokey3 with this lib before and noticed some issues.
1. The GetInfo response contained already some 2.2 members, which made serde unhappy, so I added all of the 2.2 fields (although, we _should_ ignore all unknown keys, but serde_indexed doesn't seem to have this functionality)
2. `getRetries` requires the PIN protocol in CTAP 2.0, but not anymore in 2.1.
3. Sadly, my NK3 still error-ed out with MissingParameter, because it has a bug and reports full 2.1 support, but still requires the PIN protocol (see [here](https://github.com/Nitrokey/nitrokey-fido2-firmware/issues/77)). So I changed the hard error into a soft error, as the displaying of the retry counter is optional anyways.
=> Fix getRetries CTAP 2.0 / 2.1 behavior

libwebauthn/examples/cred_management.rs, libwebauthn/src/management.rs, libwebauthn/src/management/credential_management.rs, libwebauthn/src/proto/ctap2/cbor/request.rs, libwebauthn/src/proto/ctap2/mod.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/model/bio_enrollment.rs, libwebauthn/src/proto/ctap2/model/credential_management.rs, libwebauthn/src/proto/ctap2/protocol.rs
=> Implement Credential Management

libwebauthn/src/proto/ctap2/model/client_pin.rs
Fixes #74, causing an error with `change_pin_hid` with Solo2 keys. 
Unconditional skips aren't supported  by `serde-indexed` - this includes either `serde(skip_serializing)` and `serde(skip)`.
This change works around the limitation by using `skip_serializing_if` alongside a method which returns always true.
Long term fix is https://github.com/trussed-dev/serde-indexed/pull/14 (unmerged since Feb 2024) - pinged authors and contributors to see if this can be merged.
=> Fix #74: Workaround for serde-indexed not supporting serde(skip) yet

libwebauthn/src/lib.rs, libwebauthn/src/management/bio_enrollment.rs, libwebauthn/src/management/credential_management.rs, libwebauthn/src/proto/ctap2/protocol.rs, libwebauthn/src/transport/error.rs
There still are a bunch of other unwraps in the code (some of which you can even see in this patch), mostly parsing either CBOR or other binary stuff in the crypto-section.
Not sure, if we want to address them here as well, and if so, how. 
For CBOR-related things, we could basically also just return the serde errors?
=> Fix #69: Do not unwrap when extracting data from responses

.gitmodules, Cargo.lock, libwebauthn/Cargo.toml
PR https://github.com/mcginty/snow/pull/185 was merged into snow v0.10.0-alpha.1, adding support for P-256. This is required by the CTAP Hybrid Transport spec.
This PR deprecates the snow fork, in favour of the new upstream version containing my changes.
=> Ref #71: Use upstreamed snow with P-256 support

libwebauthn/examples/webauthn_cable.rs, libwebauthn/examples/webauthn_extensions_hid.rs, libwebauthn/src/fido.rs, libwebauthn/src/ops/u2f.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs
A few things going on here:
- Previously, `AuthenticatorData` was just a ByteBuf. I added it as a struct with de/serialize-functions.
- Input and Output of the extensions vary for given commands, so I made `AuthenticatorData` generic over that, and specify which extension-struct it will contain inside `MakeCredential` or `GetAssertion`. This should be totally invisible to the end-user, who will just get 'the right thing'. It does, however, make the de/serialize-code a bit messy.
- `hmac-secret` extension needs more work, but this PR was already getting quite big, so I figured, this would be better in a follow-up PR.
Tested credBlob, minPinLength and credProtect extension with my Yubikey Bio successfully.
=> Implement basic extensions infrastructure

README.md
=> Update the readme with examples

libwebauthn/examples/webauthn_extensions_hid.rs, libwebauthn/src/ops/u2f.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/model/client_pin.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs, libwebauthn/src/transport/ble/channel.rs, libwebauthn/src/transport/cable/channel.rs, libwebauthn/src/transport/channel.rs, libwebauthn/src/transport/hid/channel.rs, libwebauthn/src/transport/mod.rs, libwebauthn/src/webauthn.rs
This is working, but I'll mark it as WIP for now, as we may want to incorporate extensions-related issues in here as well.
Noteworthy things here:
- `Ctap2PinUvAuthProtocol` got a new function to create a boxed `PinUvAuthProtocol`-object out of a given protocol version, as handing around the boxed dyn-trait object is quite annoying.
- I extended what will be saved in the channel wrt to auth_token-stuff, as we need the shared_secret, the key_agreement and the used protocol version in order to be able to process the HMAC input AND output. At least, with this, I could de-duplicate `get_uv_auth_token()`. However, there is also potentially a problem here, as we currently always create a shared_secret, which we shouldn't do in the CTAP 2.0 case, see also …
=> Implement HMAC secret extension

libwebauthn/examples/prf_test.rs, libwebauthn/examples/webauthn_extensions_hid.rs, libwebauthn/examples/webauthn_prf_hid.rs, libwebauthn/src/ops/u2f.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs, libwebauthn/src/transport/error.rs, libwebauthn/src/webauthn.rs
This is split into two commits:
The first one implements the translation layer from Ctap2 to Webauthn for MakeCredentials (which was, until now a No-op, and thus not implemented)
The second one then implements PRF on top of that (and the translation layer for GetAssertion).
The only 'ugly' bit to me is the U2F function (see the inline comment).
NOTE: This should be followed up by another PR implementing PreFlight for CTAP2. I think we only have it for U2F at the moment, but we need a filtered allow_list.
=> Implement Prf

libwebauthn/examples/prf_test.rs, libwebauthn/examples/webauthn_extensions_hid.rs, libwebauthn/examples/webauthn_prf_hid.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs, libwebauthn/src/webauthn.rs
1. Credential protection policy: 
a) Stop exposing `ctap_types` in our API and use our own implementation for the webauthn-layer (the CTAP layer still uses `ctap_types`)
b) Also support `enforce_policy`, which we can only do from the inside, as we need `Ctap2GetInfoResponse` for that. Error out, if it can't be enforced.
2. Support `credProps` extension. 
a) Pretty straight forward, except that CTAP 2.0 devices are allowed to create discoverable credentials even if they are not requested. CTAP 2.1 devices are not allowed to do that anymore. So we need `Ctap2GetInfoResponse` once again to decide
3. Switch from LargeBlobKeys extension to LargeBlob extension.
a) LargeBlob extension has "Preferred"-mode as well, so we need `Ctap2GetInfoResponse` again for deciding, if we can request it or not. …
=> More extensions

README.md, libwebauthn/examples/webauthn_cable.rs, libwebauthn/src/pin.rs, libwebauthn/src/proto/ctap2/protocol.rs, libwebauthn/src/transport/cable/channel.rs, libwebauthn/src/transport/cable/tunnel.rs, libwebauthn/src/transport/channel.rs, libwebauthn/src/webauthn.rs
See [list of commits](https://github.com/linux-credentials/libwebauthn/pull/97/commits) for individual changes.
Tested successfully with a Pixel 8 Pro running Android 15.
Creation & assertion are successful using Bitwarden on the phone.
I was originally getting a HTTP 400 error upon connecting to Google's caBLE servers:
```
DEBUG libwebauthn::transport::cable::tunnel: Connecting to tunnel server connect_url="wss://cable.ua5v.com/cable/connect/078f8a/4daa63321c9414caecee728764b0b3c9"
DEBUG rustls::anchors: add_parsable_certificates processed 148 valid and 0 invalid certs    
DEBUG tokio_tungstenite::tls::encryption::rustls: Added 148/148 native root certificates (ignored 0)    
DEBUG rustls::client::hs: No cached session for DnsName("cable.ua5v.com")    
DEBUG rustls::client::hs: Not …
```
=> Fix #52: QR-initiated hybrid transport support on Android

libwebauthn/src/transport/ble/btleplug/manager.rs, libwebauthn/src/transport/ble/btleplug/mod.rs, libwebauthn/src/transport/cable/qr_code_device.rs
* Switches from a periodic polling approach, to an event-driven discovery. It uses btleplug's event system to wait for a BLE advertisement. This is guaranteed to occur after the QR code is generated, making this safe.
* Fixes iOS discovery limitation, by removing UUID filter for BlueZ device discovery. This seems to be a limitation in BlueZ (it [wouldn't be the first](https://github.com/deviceplug/btleplug/issues/289)), that I could not find a workaround for. It should have no significant downside, however, as discovered devices that don't include the relevant service data are ignored (we do not attempt connecting to them). 
Tested on an iPhone, and Android 15. Example `webauthn_cable` succeeds consistently.
=> Hybrid transport: Switch to event-driven discovery

libwebauthn/examples/prf_test.rs, libwebauthn/src/fido.rs, libwebauthn/src/ops/u2f.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/mod.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs
- `impl Serialize for AttestedCredentialData` and `impl<T> Serialize for AuthenticatorData<T>` actually doesn't work the way it was intended, because it needs to be wrapped inside some other data type, that we don't have. So I moved that code to a stand-alone function that returns the `Vec<u8>` directly.
- Some things are not yet implemented, like appid, largeblob-write.
=> Split extensions into unsigned extensions and signed extensions inside AuthenticatorData

README.md, libwebauthn/examples/webauthn_cable.rs, libwebauthn/src/transport/ble/btleplug/manager.rs, libwebauthn/src/transport/cable/advertisement.rs, libwebauthn/src/transport/cable/channel.rs, libwebauthn/src/transport/cable/crypto.rs, libwebauthn/src/transport/cable/known_devices.rs, libwebauthn/src/transport/cable/mod.rs, libwebauthn/src/transport/cable/qr_code_device.rs, libwebauthn/src/transport/cable/tunnel.rs, libwebauthn/src/transport/error.rs
* Updates internals of CableKnownDeviceInfoStore, to make it easier to use and thread-safe.
* Adds parsing of caBLE update messages. This includes a Google-specific key (999). Due to a limitation in serde-indexed, parsing of this structure has to be done field-by-field with `serde_cbor`. To be fixed properly with #66.
* Connect to known device from saved state.
* Verifies handshake signature. Note this currently only works for linking information received on QR-initiated transactions. The protocol doesn't seen to support subsequent updates, as the ephemeral QR-code identity key is needed for verification.
=> Hybrid transport: Add state-assisted transactions

libwebauthn/src/ops/webauthn.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs
Some unsigned extensions have to be present, even if no signed extensions are present. Thus we have to decouple them.
And rename to camelCase seemed to make `Id` out of `ID`, which is needed for JSON-parsing. So we manually rename the enums in `CredentialProtectionPolicy` now, just to be sure.
=> Parse unsigned extensions, even if no signed extensions are present

Cargo.lock, libwebauthn/Cargo.toml, libwebauthn/src/transport/ble/btleplug/error.rs, libwebauthn/src/transport/error.rs
* Reduces some boilerplate
* Used in  #105 - allow making dependency non-optional, rather than for `nfc` feature only
* I plan to use this in new CBOR serialization and deserialization, as I would like to encapsulate underlying errors (more easily)
=> Use thiserror for errors

libwebauthn/src/transport/ble/channel.rs, libwebauthn/src/transport/cable/tunnel.rs, libwebauthn/src/transport/error.rs, libwebauthn/src/transport/hid/channel.rs
Fixes #103.
Also protect against mutex poisoning.
=> Make the HID channel safer (fix #103)

libwebauthn/src/proto/ctap2/model/bio_enrollment.rs, libwebauthn/src/proto/ctap2/model/client_pin.rs
I'm not entirely sure what exactly caused the problem inside serde_indexed, but these macros (particularly the one at `Ctap2GetClientPinRequest`) caused my YubikeyBIO to error out, in the PIN case with `InvalidCborType` when trying to establish a shared secret.
=> Remove leftover serde_indexed-macros

libwebauthn/src/fido.rs, libwebauthn/src/proto/ctap2/protocol.rs
This fixes a regression with serializing the WebAuthn authenticator data format.
=> fix: Serialize WebAuthn authenticator data properly

libwebauthn/src/ops/u2f.rs, libwebauthn/src/proto/ctap2/model/get_assertion.rs
We don't serialize these, so it's up to the application to repackage it. Since a single certificate is required by the standard, let's only return exactly one, removing the need to error check the length on the outside. The algorithm is also not needed.
=> Return U2F attestation statement in a way that does not require error checking in clients

libwebauthn/examples/webauthn_cable.rs, libwebauthn/examples/webauthn_extensions_hid.rs, libwebauthn/examples/webauthn_hid.rs, libwebauthn/examples/webauthn_preflight_hid.rs, libwebauthn/examples/webauthn_prf_hid.rs, libwebauthn/src/ops/webauthn.rs, libwebauthn/src/ops/webauthn/make_credential.rs, libwebauthn/src/proto/ctap2/model/make_credential.rs
Switched away from a context-less `From<MakeCredentialRequest> for Ctap2MakeCredentialRequest` implementation to a dedicated function that can additionally receive the device-info to make that transformation.
Now we also don't need to copy the original request and modify it (which was always a bit icky), but we can do the direct translation to the Ctap2-request.
=> Implement discoverable credential 'preferred'

Cargo.lock, libwebauthn/Cargo.toml, libwebauthn/src/proto/ctap2/cbor/serde.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/transport/cable/tunnel.rs
Addresses [RUSTSEC-2021-0127](https://rustsec.org/advisories/RUSTSEC-2021-0127.html).
=> Replace serde_cbor with serde_cbor_2

libwebauthn/src/fido.rs, libwebauthn/src/proto/ctap2/cbor/mod.rs, libwebauthn/src/proto/ctap2/cbor/serde.rs
As suggested by @AlfioEmanueleFresta in #136 in https://github.com/linux-credentials/libwebauthn/pull/136#pullrequestreview-3059589590 added a test for deserializing AuthData.
To be able to test this, I had to pull out the AuthenticatorDataVisitor struct to make the visit_bytes function available, I understand that this exposes the implementation details a bit, so might not be the best solution here. I'm open for suggestions.
=> extended the tests for AuthData deserialization

libwebauthn/src/ops/webauthn.rs, libwebauthn/src/pin.rs, libwebauthn/src/proto/ctap2/cbor/request.rs, libwebauthn/src/proto/ctap2/mod.rs, libwebauthn/src/proto/ctap2/model.rs, libwebauthn/src/proto/ctap2/model/client_pin.rs, libwebauthn/src/proto/ctap2/model/get_info.rs, libwebauthn/src/tests/channel.rs, libwebauthn/src/tests/mod.rs, libwebauthn/src/transport/mod.rs, libwebauthn/src/webauthn/pin_uv_auth_token.rs
This PR adds another layer of testing opportunities, by introducing a `TestChannel` that can be pre-filled with expected requests and associated responses it should give.
I have used this to test `user_verification(..)` in various states of complexity, and discovered a few bugs along the way.
Notable changes to make this possible:
- `PinUvAuthProtocol`s get a deterministic private key, to 'predict' crypto results (for testing only!)
- Some (the ones I needed) Ctap2-response structs got a `#[cfg_attr(test, derive(SerializeIndexed))]` to serialize them to CBOR, before sending it back as if it were a real message from a device. This should be easy to extend to other response structs, once they are needed.
- Removed a second, subsequent `GetInfo`-call, by simply reusing the result of the …
=> Add more UV-negotiation tests

libwebauthn/Cargo.lock, libwebauthn/Cargo.toml, libwebauthn/src/proto/ctap2/preflight.rs, libwebauthn/src/tests/basic_ctap2.rs, libwebauthn/src/tests/mod.rs, libwebauthn/src/tests/prf.rs, libwebauthn/src/transport/mock/channel.rs, libwebauthn/src/transport/mock/mod.rs, libwebauthn/src/transport/mod.rs, libwebauthn/src/transport/virt/device.rs, libwebauthn/src/transport/virt/mod.rs, libwebauthn/src/webauthn.rs, libwebauthn/src/webauthn/pin_uv_auth_token.rs
Note: Needs rebasing after #149 lands, as this built on top of it.
Since the callback structure of nitrokeys/trusseds firmware makes it hard to have a 'normal' device, that can handle more than one consecutive requests without losing state, and after banging my head against this for quite some time, I opted for a rather blunt, but hopefully effective (enough) solution: Simple message passing. 
Now the callback-function is started in its own thread and requests+responses are passed back and forth via normal channels. 
I also removed the filesystem storage and went back to RAM storage only. This way, it should be possible to have multiple devices in parallel without any interference. As long as the device object lives, state is kept and things like "establishing shared secret, getting …
=> Switch virt device to RAM only and use message passing to allow for state to be kept across device lifetime
